# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Neurobbery
tagline:          'A Jekyll theme'
description:      'Miscellaneous thoughts to rob your neurons.'
url:              
baseurl:          ""

author:
  name:           'Neurobber'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

# Plogins
plugins:  [jekyll-paginate]

gems: [jekyll-paginate]
